apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      requests:
        cpu: "0.5"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

#In this example:

#The pod requests a minimum of 0.5 vCPUs and 512MB of memory.
#The pod is limited to using a maximum of 1 vCPU and 1GB of memory.
